### ISSUE TITLE
w2v_vocab.pkl和w2v_vector.pkl文件

### ISSUE THREAD

**Issue by boyoi** [BaberMuyu/2020CCF-NER#1]
大佬大佬，请问w2v_vocab.pkl和w2v_vector.pkl文件是您自己生成的么，我没有找到相关生成的代码

**Comment by BaberMuyu** [comment]
在data/word2vec.py中，在main.py中en_prep可以调用函数从词向量文件生成这俩个文件

**Comment by boyoi** [comment]
好的好的，谢谢大佬
