### ISSUE TITLE
TextEncoder处理FLAT input时，char_word_mask及part_size计算方式的问题

### ISSUE THREAD

**Issue by RacleRay** [BaberMuyu/2020CCF-NER#10]
请问，代码中，在计算 word_mask，part_size等 （NERModelFitting.py 中 collate_fn_test 方法），这种有点奇怪的方式，有什么依据吗？
如果只是处理为正常的 FLAT 输入，在我看来结果是错的。还有这个奇怪的 mask，在 Model 的 Tranformer 计算时，明显已经把正常的 text token 都 mask 掉了。
所以，冒昧想问一下，这么处理有没有什么理由，还是说，恰巧得到了比较好的分数，或者上传的不是最终的正确代码。 
还请不吝赐教，谢谢

**Comment by BaberMuyu** [comment]
就是为了把词向量拼接到bert的字向量后面得到FLAT的输入，虽然看着比较奇怪，但我也没想到更有效率的方法。如果您能够想出更好的方法，还请分享一下。此外，希望您在提问时，不要提出一些令人不悦的猜测，这不会对解决问题有任何积极的作用。
谢谢！

**Comment by RacleRay** [comment]
谢谢谢谢，抱歉想些啥就直接说了，表达有点问题。。已经明白那一段的意思了，机智! 我自己瞎写的方式也只是记录 char 阶段的长度，再一个一个拼接上，效率低一些。还是大佬的方法简洁一些。
另外，指出一个我问题里面的一个错误：这么做没有mask掉正常的词，我犯傻了。只是 char和 lattice的embedding 会有叠加的部分，不过效果很 nice！
谢谢您的分享，祝您工作学习愉快！
