### ISSUE TITLE
缺少train_data

### ISSUE THREAD

**Issue by yolanda182** [BaberMuyu/2020CCF-NER#11]
大佬，打扰一下。我跑代码发现：No such file or directory: '/Users//2020CCF-NER-main/data/ccf2020/train_data/'
是需要将另外将数据放在ccf2020文件夹下面吗？

**Comment by BaberMuyu** [comment]
是的，把比赛数据放在ccf2020文件夹下

**Comment by yolanda182** [comment]
大佬您好！我还想请问一下：
1. 因为报名已经截止了，我没法直接下载比赛数据，发现文件夹里有train_data.json文件，将这个转化为txt文件就是比赛的数据吗？
2. 或者您可以告诉我可以有什么途径去下载这个数据吗？
万分感激！！！

**Comment by BaberMuyu** [comment]
文件夹里的train_data.json 是从比赛数据集生成的文件，可以直接使用，将convert那一步直接注释掉即可。这个比赛的数据集没什么价值，建议直接使用clue数据集。

**Comment by yolanda182** [comment]
感谢大佬！！！万分感激🙏
