### ISSUE TITLE
AttributeError: 'str' object has no attribute 'detach'

### ISSUE THREAD

**Issue by FLxuRu** [BaberMuyu/2020CCF-NER#5]
encoder.py这个文件中的vec是str类型，vec.detach()这样写会报错，请问作者这里是不是去掉detach()
def get_bert_vec(self, text, text_mask, text_pos=None):
        if text_pos is None:
            _, _, text_vecs = self.bert(text, text_mask)
        else:
            _, _, text_vecs = self.bert(text, text_mask, position_ids=text_pos)
        text_vecs = list(text_vecs)
        if self.detach_ptm_flag:
            for i, vec in enumerate(text_vecs):
                text_vecs[i] = vec.detach()
        return text_vecs

**Comment by BaberMuyu** [comment]
这是transformers的版本问题，我用的是transformers 3.0.2
