### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by clear-love-k** [BaberMuyu/2020CCF-NER#9]
小白提问：
在本地执行时运行一会儿电脑崩溃直接关机，想着是配置太低了跑不了
然后我把项目放到了kaggle上执行，
为什么还是会出现out of memory的问题？

**Comment by RacleRay** [comment]
第一，代码预处理 io 操作全是直接读进内存处理，尤其是 word vec 文件处理，会消耗大量内存。自己看看数据处理代码的部分，优化一下 io。最好单独把预处理，和训练部分，分离开，单独运行。如果没有开始训练就 out of memory 那就是这个问题了。

第二，如果开始训练还 out，显卡显存不够了，kaggle好像是 11G。减小batch size。也可以改半精度，就是FGM代码也要该。或者用Colab，看能不能白嫖到 16G 卡。

**Comment by clear-love-k** [comment]
好的好的，**感谢**！我再多看看代码
